---
- name: bridges | Managing OVS Bridges
  openvswitch_bridge:
    bridge: "{{ item['name'] }}"
    parent: "{{ item['parent']|default(omit) }}"
    fail_mode: "{{ item['fail_mode']|default('standalone') }}"
    state: "{{ item['state'] }}"
    timeout: "{{ item['timeout']|default(omit) }}"
    vlan: "{{ item['vlan']|default(omit) }}"
  become: true
  with_items: '{{ openvswitch_bridges_list }}'
  when: openvswitch_bridges_list is defined
