---
# tasks file for ansible-openvswitch
- name: main | Gather services status
  ansible.builtin.service_facts:
  changed_when: false

- name: main | Include Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: main | Include service tasks
  ansible.builtin.include_tasks: service.yml

- name: main | Include system_tuning tasks
  ansible.builtin.include_tasks: system_tuning.yml

- name: main | Include bridges tasks
  ansible.builtin.include_tasks: bridges.yml

- name: main | Include ports tasks
  ansible.builtin.include_tasks: ports.yml
