---
# tasks file for ansible-openvswitch
- name: Gather services status.
  ansible.builtin.service_facts:

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: service.yml

- include_tasks: system_tuning.yml

- include_tasks: bridges.yml

- include_tasks: ports.yml
