---
# tasks file for ansible-openvswitch
- name: main | Gather services status
  ansible.builtin.service_facts:
  changed_when: false

- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.include_tasks: service.yml

- ansible.builtin.include_tasks: system_tuning.yml

- ansible.builtin.include_tasks: bridges.yml

- ansible.builtin.include_tasks: ports.yml
