---
- name: ports | Managing OVS Ports
  openvswitch.openvswitch.openvswitch_port:
    bridge: "{{ item[0]['bridge'] }}"
    port: "{{ item[1]['port'] }}"
    state: "{{ item[1]['state'] }}"
    tag: "{{ item[1]['tag']|default(omit) }}"
    timeout: "{{ item[0]['timeout']|default(omit) }}"
  become: true
  loop: "{{ openvswitch_ports|subelements('ports') }}"
  when: 
    - openvswitch_ports is defined
    - not ansible_check_mode
