---
- name: system_tuning | Managing sysctl
  ansible.builtin.sysctl:
    name: "{{ item['name'] }}"
    value: "{{ item['value'] }}"
    state: "present"
  become: true
  loop: "{{ openvswitch_system_tuning }}"
  when: openvswitch_system_tuning is defined
